# base image
FROM node:14.17.0

# set working directory
WORKDIR C:\Users\User\Desktop\monpfe
# install and cache app dependencies
COPY package.json ./
RUN npm install
RUN npm install -g @angular/cli@12.2.16

# add app
COPY . .

EXPOSE 8080

# start app
CMD ng serve --host 0.0.0.0